services:
  backend:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/code:ro
    environment:
      - DATABASE_URL=
    command: wait-for-it db:5432 -- alembic upgrade head
    ports:
      - "1000:8001"

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    ports:
      - "5433:5432"

volumes:
  postgres_data: