"""update_product

Revision ID: 52ebf611febc
Revises: b5f1c32bd922
Create Date: 2025-05-22 10:38:52.296125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ebf611febc'
down_revision: Union[str, None] = 'b5f1c32bd922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('vender_code', sa.String(length=200), nullable=False))
    op.drop_column('products', 'article_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('article_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('products', 'vender_code')
    # ### end Alembic commands ###
