"""update_products

Revision ID: 5864a6385c95
Revises: 8fe65b20dc51
Create Date: 2025-06-05 13:23:21.848297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5864a6385c95'
down_revision: Union[str, None] = '8fe65b20dc51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('first_market', sa.String(length=250), nullable=False))
    op.drop_column('products', 'fisrt_market')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('fisrt_market', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_column('products', 'first_market')
    # ### end Alembic commands ###
