"""update_products

Revision ID: 8fe65b20dc51
Revises: f68c115f5cd8
Create Date: 2025-06-05 11:07:42.557540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe65b20dc51'
down_revision: Union[str, None] = 'f68c115f5cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('fisrt_market', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'fisrt_market')
    # ### end Alembic commands ###
