"""update_db

Revision ID: abf4540539d5
Revises: edadd4019c72
Create Date: 2025-05-21 15:50:32.837605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf4540539d5'
down_revision: Union[str, None] = 'edadd4019c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_price', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Integer(), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_comparisons_id'), 'product_comparisons', ['id'], unique=False)
    op.drop_index('ix_competitors_id', table_name='competitors')
    op.drop_table('competitors')
    op.add_column('products', sa.Column('artcile_number', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('market_link', sa.Text(), nullable=False))
    op.add_column('products', sa.Column('name_product', sa.Text(), nullable=False))
    op.add_column('products', sa.Column('image', sa.Text(), nullable=False))
    op.add_column('products', sa.Column('price', sa.Integer(), nullable=False))
    op.drop_column('products', 'vender_code')
    op.drop_column('products', 'step')
    op.drop_column('products', 'min_price')
    op.drop_column('products', 'product_link')
    op.drop_column('products', 'max_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('max_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('product_link', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('min_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('step', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('vender_code', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('products', 'price')
    op.drop_column('products', 'image')
    op.drop_column('products', 'name_product')
    op.drop_column('products', 'market_link')
    op.drop_column('products', 'artcile_number')
    op.create_table('competitors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vender_code_pay', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vender_code_market', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='competitors_pkey')
    )
    op.create_index('ix_competitors_id', 'competitors', ['id'], unique=False)
    op.drop_index(op.f('ix_product_comparisons_id'), table_name='product_comparisons')
    op.drop_table('product_comparisons')
    # ### end Alembic commands ###
