"""update_product

Revision ID: b5f1c32bd922
Revises: abf4540539d5
Create Date: 2025-05-22 10:09:08.327916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5f1c32bd922'
down_revision: Union[str, None] = 'abf4540539d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('article_number', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('pieces_product', sa.Integer(), nullable=True))
    op.drop_column('products', 'artcile_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('artcile_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('products', 'pieces_product')
    op.drop_column('products', 'article_number')
    # ### end Alembic commands ###
