"""update_tables

Revision ID: f68c115f5cd8
Revises: dd5dcbae07fe
Create Date: 2025-05-29 17:28:53.416972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68c115f5cd8'
down_revision: Union[str, None] = 'dd5dcbae07fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_comparisons_product_id_fkey'), 'product_comparisons', type_='foreignkey')
    op.create_foreign_key(None, 'product_comparisons', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('seller_products_product_id_fkey'), 'seller_products', type_='foreignkey')
    op.drop_constraint(op.f('seller_products_seller_id_fkey'), 'seller_products', type_='foreignkey')
    op.create_foreign_key(None, 'seller_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'seller_products', 'sellers', ['seller_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seller_products', type_='foreignkey')
    op.drop_constraint(None, 'seller_products', type_='foreignkey')
    op.create_foreign_key(op.f('seller_products_seller_id_fkey'), 'seller_products', 'sellers', ['seller_id'], ['id'])
    op.create_foreign_key(op.f('seller_products_product_id_fkey'), 'seller_products', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'product_comparisons', type_='foreignkey')
    op.create_foreign_key(op.f('product_comparisons_product_id_fkey'), 'product_comparisons', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
